baseURL: "https://pnm.tf/"
title: pnm.tf
theme: papermod

params:
  profileMode:
    enabled: true
    title: "*Paul-Nicolas Madelaine*"
    imageUrl: "me.jpg"
    buttons:
      - name: Blog
        url: "/posts"
  socialIcons:
    - name: github
      url: "https://github.com/pnmadelaine"
    - name: mastodon
      url: "https://mamot.fr/@pnm"
    - name: lichess
      url: "https://lichess.org/@/pnmadelaine"
    - name: email
      url: "mailto:pnm@pnm.tf"
    - name: signal
      url: "signal"
    - name: rss
      url: "index.xml"
